services:
  app:
    build: app
    ports:
      - 8000:8000
    environment:
      OPENAI_API_KEY: 'put your api key here'
      DATABASE_URI: 'clickhouse+native://localhost/default'

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000